[package]
name = "textnonce"
version = "0.6.3"
description = "Text based random nonce generator"
authors = [ "Mike Dilger <mike@optcomp.nz>" ]
readme = "README.md"
repository = "https://github.com/mikedilger/textnonce"
documentation = "https://docs.rs/textnonce"
license = "MIT OR Apache-2.0"
keywords = [ "nonce", "random" ]

[dev-dependencies]
bincode = "0.8"

[dependencies]
rand = "0.5"
chrono = "0.4"
byteorder = "1.2"
base64 = "0.6"
serde = "1.0"
serde_derive = "1.0"

clippy = { version = "^0", optional = true }
