[package]
name = "textnonce"
version = "0.3.4"
description = "Text based random nonce generator"
authors = [
        "Mike Dilger <mike@optcomp.nz>",
        "Konstantin Stepanov <milezv@gmail.com>"
        ]
readme = "README.md"
repository = "https://github.com/mikedilger/textnonce"
documentation = "https://mikedilger.github.io/textnonce"
license = "MIT OR Apache-2.0"
keywords = [ "nonce", "random" ]

[features]
default = [ ]

[dependencies]
rand = "^0.3"
time = "^0.1"
rustc-serialize = "^0.3"
serde = { version = "0.7", optional = true }
clippy = { version = "^0", optional = true }
