[package]
name = "textnonce"
version = "0.5.0"
description = "Text based random nonce generator"
authors = [ "Mike Dilger <mike@optcomp.nz>" ]
readme = "README.md"
repository = "https://github.com/mikedilger/textnonce"
documentation = "https://mikedilger.github.io/textnonce"
license = "MIT OR Apache-2.0"
keywords = [ "nonce", "random" ]

[dev-dependencies]
bincode = "1.0.0-alpha5"

[dependencies]
rand = "0.3"
time = "0.1"
base64 = "0.4"
serde = "0.9"
serde_derive = "0.9"

clippy = { version = "^0", optional = true }
